service: invoiceocr

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8


functions:
  ocr:
    handler: handler.ocr
    events:
      - http:
          path: ocr
          method: post


